name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} --password-stdin.

      - name: Pull backend Docker image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            'docker pull istaprasad/expense-tracker:backend'

      - name: Pull frontend Docker image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            'docker pull istaprasad/expense-tracker:frontend'

      - name: Stop and remove existing containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            'docker stop expense_b || true && docker rm expense_b || true'
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            'docker stop expense_f || true && docker rm expense_f || true'

      - name: Run backend container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            'docker run -d --name expense_b -p 4000:4000 \
             -e PORT=${{ secrets.PORT }} \
             -e LINK=${{ secrets.LINK }} \
             -e MONGO_URI=${{ secrets.MONGO_URI }} \
             -e SECRET=${{ secrets.SECRET }} \
             istaprasad/expense-tracker:backend'

      - name: Run frontend container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} \
            'docker run -d --name expense_f -p 5173:5173 \
             -e VITE_APP_LINKED=${{ secrets.VITE_APP_LINKED }} \
             istaprasad/expense-tracker:frontend'
