name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: scp -r -o StrictHostKeyChecking=no ./ ubuntu@your-ec2-ip:/path/to/deploy

      - name: SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-ip << 'EOF'
            cd /path/to/deploy
            echo "PORT=${{ secrets.PORT }}" >> .env
            echo "LINK=${{ secrets.LINK }}" >> .env
            echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
            echo "SECRET=${{ secrets.SECRET }}" >> .env
            echo "VITE_APP_LINKED=${{ secrets.VITE_APP_LINKED }}" >> .env
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            docker-compose pull
            docker-compose up -d
          EOF
